import "../output.css";
import Header from "../components/Header";
import Banner from "../components/Banner";
export const metadata = {
  title: 'FrontEnd Test Suitmedia',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen bg-white">
        <Header />
        <Banner />
        {children}
        </div></body>
    </html>
  )
}
